### ISSUE TITLE
Unparseable date bug on create blog

### ISSUE THREAD

**Issue by tamiragun** [tamiragun/Doc2Blog#45]
The blog POST endpoint is working (as in, no HTTP errors are given and the database is updating and the front end can continue unhampered, but the server is throwing this error:

```
java.text.ParseException: Unparseable date: "2022-02-14"
	at java.base/java.text.DateFormat.parse(DateFormat.java:399)
	at com.ProjTeam.Doc2Blog.blogPosts.BlogPostController.getBlogPosts(BlogPostController.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by tamiragun** [comment]
Closed with commit [e31a897](https://github.com/tamiragun/Doc2Blog/commit/e31a8970f50d972d50bb5e0fed39ba20ed09daea)
